version: '3.8'

services:
  movie-searcher-bot:
    build: .
    container_name: movie-searcher-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./:/app